const bars = [
    {
        name: "L'atelier B",
        city: "Bordeaux",
        address: "29 rue de la Rousselle 33300 Bordeaux",
        imageUrl: "",
        website: "https://www.atelierb-bordeaux.fr/",
        phone: "05 57 99 63 98",
        game_day: "Mercredi",
        game_time: "18h30",
        created: new Date()
    },
    {
        name: "Le Beau Jeu",
        city: "Bordeaux",
        address: "22 rue du Chai des Farines 33300 Bordeaux",
        imageUrl: "",
        website: "https://lebeaujeubordeaux.com/",
        phone: "09 55 71 82 78",
        game_day: "Mardi",
        game_time: "19h00",
        created: new Date()
    },
    {
        name: "Le Quinte & Sens",
        city: "Bordeaux",
        address: "35 rue de Gironde 33300 Bordeaux",
        imageUrl: "",
        website: "https://www.facebook.com/profile.php?id=61550036344982",
        phone: "06 69 96 86 01",
        game_day: "Jeudi",
        game_time: "19h30",
        created: new Date()
    },
    {
        name: "O'Tiap",
        city: "Bordeaux",
        address: "158 rue Emile Combes 33000 Bordeaux",
        imageUrl: "",
        website: "https://otiap.fr/",
        phone: "09 78 80 84 29",
        game_day: "Jeudi",
        game_time: "19h00",
        created: new Date()
    },
    {
        name: "Les Broc's",
        city: "Bordeaux",
        address: "16 place Canteloup 33800 Bordeaux",
        imageUrl: "",
        website: "https://les-brocs.com/",
        phone: "07 67 44 44 26",
        game_day: "Dimanche",
        game_time: "17h00",
        created: new Date()
    },
    {
        name: "Le Mosaic",
        city: "Bordeaux",
        address: "269 rue Judaïque 33000 Bordeaux",
        imageUrl: "",
        website: "https://www.instagram.com/mosaic.bieres_artisanales/",
        phone: "05 56 98 84 66",
        game_day: "Samedi",
        game_time: "16h00",
        created: new Date()
    },
    {
        name: "Le Magnus Pub",
        city: "Bordeaux",
        address: "32 rue de Cheverus 33000 Bordeaux",
        imageUrl: "",
        website: "https://www.instagram.com/magnus_pub/",
        phone: "05 56 98 84 66",
        game_day: "Dimanche",
        game_time: "18h00",
        created: new Date()
    },
    {
        name: "Les Chaises",
        city: "Paris",
        address: "33 rue de la Chine 75020 Paris", 
        imageUrl: "",
        website: "https://www.facebook.com/leschaises.lebar/",
        phone: "09 51 65 08 24",
        game_day: "Mardi",
        game_time: "19h00",
        created: new Date()
    },
    {
        name: "La Taverne de Fwinax",
        city: "Paris",
        address: "32 rue Traversière 75012 Paris",
        imageUrl: "",
        website: "https://www.facebook.com/p/La-Taverne-de-Fwinax-100087501427363/",
        phone: "07 69 26 46 87",
        game_day: "Mercredi",
        game_time: "18h30",
        created: new Date()
    },
    {
        name: "Luppolo",
        city: "Paris",
        address: "31 rue Victor Massé 75009 Paris",
        imageUrl: "",
        website: "https://luppolo-bar.fr/",
        phone: "09 83 87 92 08",
        game_day: "Jeudi",
        game_time: "19h00",
        created: new Date()
    },
    {
        name: "Le Duchesse",
        city: "Paris",
        address: "36 rue de l'Orillon 75011 Paris",
        imageUrl: "",
        website: "https://leduchesseparis.fr/",
        phone: "07 62 38 87 54",
        game_day: "Jeudi",
        game_time: "20h00",
        created: new Date()
    },
    {
        name: "Les Grands Gamins",
        city: "Paris",
        address: "19 rue de Cléry 75002 Paris",
        imageUrl: "",
        website: "https://lesgrandsgaminsparis.fr/",
        phone: "06 77 60 21 33",
        game_day: "Dimanche",
        game_time: "19h30",
        created: new Date()
    },
    {
        name: "Café de la Cité",
        city: "Nantes",
        address: "5 rue de Valmy 44000 Nantes",
        imageUrl: "",
        website: "https://cafedelacite.fr/",
        phone: "02 51 88 21 21",
        game_day: "Vendredi",
        game_time: "18h00",
        created: new Date()
    },
    {
        name: "Bacardy",
        city: "Nantes",
        address: "2 place Ernest Breant 44110 Chateaubriant",
        imageUrl: "",
        website: "https://villesetshopping.fr/chateaubriant/vitrine/le-bacardy/",
        phone: "02 40 81 02 32",
        game_day: "Vendredi",
        game_time: "18h00",
        created: new Date()
    },
    {
        name: "Reine de Coeur",
        city: "Rennes",
        address: "48 rue de Saint-Brieuc 35000 Rennes",
        imageUrl: "",
        website: "https://www.lareinedecoeur.fr/",
        phone: "02 99 59 15 31",
        game_day: "Lundi",
        game_time: "20h00",
        created: new Date()
    },
    {
        name: "Babazula",
        city: "Rennes",
        address: "182 Avenue Général George S. Patton 35700 Rennes",
        imageUrl: "",
        website: "https://www.facebook.com/Babazula.bar/",
        phone: "09 51 95 37 67",
        game_day: "Mardi",
        game_time: "19h00",
        created: new Date()
    },
    {
        name: "Evasion",
        city: "Rennes",
        address: "29 Grande Rue Saint-Michel 31400 Toulouse",
        imageUrl: "",
        website: "https://www.facebook.com/levasion.bar/",
        phone: "05 81 97 03 45",
        game_day: "Jeudi",
        game_time: "19h00",
        created: new Date()
    },
    {
        name: "Bob",
        city: "Lyon",
        address: "12 Rue Imbert-Colomès 69001 Lyon",
        imageUrl: "",
        website: "https://www.boblyon.fr/",
        phone: "06 22 89 95 10",
        game_day: "Mercredi",
        game_time: "19h00",
        created: new Date()
    },
    {
        name: "Bar Bu",
        city: "Lyon",
        address: "21 Quai de Bondy 69005 Lyon",
        imageUrl: "",
        website: "https://www.facebook.com/LeBarBuLyon/",
        phone: "04 78 72 15 44",
        game_day: "Lundi",
        game_time: "19h30",
        created: new Date()
    },
    {
        name: "Le Petit Bouclard",
        city: "Lyon",
        address: "5 rue des Trois Pierres 69007 Lyon",
        imageUrl: "",
        website: "https://lepetitbouclard.fr/",
        phone: "04 72 94 33 63",
        game_day: "Dimanche",
        game_time: "16h30",
        created: new Date()
    },
    {
        name: "Rebuffy",
        city: "Montpellier",
        address: "2 rue Rebuffy 34000 Montpellier",
        imageUrl: "",
        website: "https://www.facebook.com/p/Rebuffy-Pub-100057121043395/",
        phone: "04 67 66 32 76",
        game_day: "Mercredi",
        game_time: "18h00",
        created: new Date()
    },
];

module.exports = bars