const tournaments = [
    {
        id: 1,
        name: "Tournoi L'Atelier B",
        city: "Bordeaux",
        game_day: "Mercredi",
        game_time: "18h30",
        created: new Date(),
    },
    {   id: 2,
        name: "Tournoi Le Beau Jeu",
        city: "Bordeaux",
        game_day: "Mardi",
        game_time: "19h00",
        created: new Date()
    },
    {   id: 3,
        name: "Tournoi Le Quinte & Sens",
        city: "Bordeaux",
        game_day: "Jeudi",
        game_time: "19h30",
        created: new Date()
    },
    {   id: 5,
        name: "Tournoi Les Broc's",
        city: "Bordeaux",
        game_day: "Dimanche",
        game_time: "17h00",
        created: new Date()
    },
    {   id: 6,
        name: "Tournoi Le Magnus Pub",
        city: "Bordeaux",
        game_day: "Dimanche",
        game_time: "18h00",
        created: new Date()
    },
    {   id: 8,
        name: "Tournoi Les Chaises",
        city: "Paris",
        game_day: "Mardi",
        game_time: "19h00",
        created: new Date()
    },
    {   id: 9,
        name: "Tournoi La Taverne de Fwinax",
        city: "Paris",
        game_day: "Mercredi",
        game_time: "18h30",
        created: new Date()
    },
    {   id: 10,
        name: "Tournoi Luppolo",
        city: "Paris",
        game_day: "Jeudi",
        game_time: "19h00",
        created: new Date()
    },
    {   id: 12,
        name: "Tournoi Les Grands Gamins",
        city: "Paris",
        game_day: "Dimanche",
        game_time: "19h30",
        created: new Date()
    },
    {   id: 13,
        name: "Tournoi Café de la Cité",
        city: "Nantes",
        game_day: "Vendredi",
        game_time: "18h00",
        created: new Date()
    },
    {   id: 14,
        name: "Tournoi Bacardy",
        city: "Nantes",
        game_day: "Vendredi",
        game_time: "18h00",
        created: new Date()
    },
    {   id: 15,
        name: "Tournoi Reine de Coeur",
        city: "Rennes",
        game_day: "Lundi",
        game_time: "20h00",
        created: new Date()
    },
    {   id: 16,
        name: "Tournoi Babazula",
        city: "Rennes",
        game_day: "Mardi",
        game_time: "19h00",
        created: new Date()
    },
    {   id: 17,
        name: "Tournoi Evasion",
        city: "Toulouse",
        game_day: "Jeudi",
        game_time: "19h00",
        created: new Date()
    },
    {   id: 18,
        name: "Tournoi Bob",
        city: "Lyon",
        game_day: "Mercredi",
        game_time: "19h00",
        created: new Date()
    },
    {   id: 20,
        name: "Tournoi Le Petit Bouclard",
        city: "Lyon",
        game_day: "Dimanche",
        game_time: "16h30",
        created: new Date()
    },
    {   id: 21,
        name: "Tournoi Rebuffy",
        city: "Montpellier",
        game_day: "Mercredi",
        game_time: "18h00",
        created: new Date()
    },
];

module.exports = tournaments