const tournaments = [
    {
        id: 1,
        name: "L'Atelier B",
        city: "Bordeaux",
        game_day: "Mercredi",
        game_time: "18h30",
        created: new Date(),
    },
    {   id: 2,
        name: "Le Beau Jeu",
        city: "Bordeaux",
        game_day: "Mardi",
        game_time: "19h00",
        created: new Date()
    },
    {   id: 3,
        name: "Le Quinte & Sens",
        city: "Bordeaux",
        game_day: "Jeudi",
        game_time: "19h30",
        created: new Date()
    },
    {   id: 4,
        name: "O'Tiap",
        city: "Bordeaux",
        game_day: "Jeudi",
        game_time: "19h00",
        created: new Date()
    },
    {   id: 5,
        name: "Les Broc's",
        city: "Bordeaux",
        game_day: "Dimanche",
        game_time: "17h00",
        created: new Date()
    },
    {   id: 6,
        name: "Le Magnus Pub",
        city: "Bordeaux",
        game_day: "Dimanche",
        game_time: "18h00",
        created: new Date()
    },
    {   id: 7,
        name: "Le Mosaic",
        city: "Bordeaux",
        game_day: "Samedi",
        game_time: "16h00",
        created: new Date()
    },
    {   id: 8,
        name: "Les Chaises",
        city: "Paris",
        game_day: "Mardi",
        game_time: "19h00",
        created: new Date()
    },
    {   id: 9,
        name: "La Taverne de Fwinax",
        city: "Paris",
        game_day: "Mercredi",
        game_time: "18h30",
        created: new Date()
    },
    {   id: 10,
        name: "Luppolo",
        city: "Paris",
        game_day: "Jeudi",
        game_time: "19h00",
        created: new Date()
    },
    {   id: 11,
        name: "Le Duchesse",
        city: "Paris",
        game_day: "Jeudi",
        game_time: "20h00",
        created: new Date()
    },
    {   id: 12,
        name: "Les Grands Gamins",
        city: "Paris",
        game_day: "Dimanche",
        game_time: "19h30",
        created: new Date()
    },
    {   id: 13,
        name: "Café de la Cité",
        city: "Nantes",
        game_day: "Vendredi",
        game_time: "18h00",
        created: new Date()
    },
    {   id: 14,
        name: "Bacardy",
        city: "Nantes",
        game_day: "Vendredi",
        game_time: "18h00",
        created: new Date()
    },
    {   id: 15,
        name: "Reine de Coeur",
        city: "Rennes",
        game_day: "Lundi",
        game_time: "20h00",
        created: new Date()
    },
    {   id: 16,
        name: "Babazula",
        city: "Rennes",
        game_day: "Mardi",
        game_time: "19h00",
        created: new Date()
    },
    {   id: 17,
        name: "Evasion",
        city: "Toulouse",
        game_day: "Jeudi",
        game_time: "19h00",
        created: new Date()
    },
    {   id: 18,
        name: "Bob",
        city: "Lyon",
        game_day: "Mercredi",
        game_time: "19h00",
        created: new Date()
    },
    {   id: 19,
        name: "Le Bar BU",
        city: "Lyon",
        phone: "04 78 72 15 44",
        game_day: "Lundi",
        game_time: "19h30",
        created: new Date()
    },
    {   id: 20,
        name: "Le Petit Bouclard",
        city: "Lyon",
        game_day: "Dimanche",
        game_time: "16h30",
        created: new Date()
    },
    {   id: 21,
        name: "Rebuffy",
        city: "Montpellier",
        game_day: "Mercredi",
        game_time: "18h00",
        created: new Date()
    },
];

module.exports = tournaments